
export const PRODUCTECO_END = "PRODUCTECO_END";
export const PRODUCTECO_FAIL = "PRODUCTECO_FAIL";
export const ADD_PRODUCT_ECO_START = "ADD_PRODUCT_ECO_START";


export const GET_PRODUCTECO_SUCCESS = "GET_PRODUCTECO_SUCCESS";
export const PRODUCTECO_SUCCESS = "PRODUCTECO_SUCCESS";
export const PRODUCTECO_FILTER = "PRODUCTECO_FILTER";

