export const ADDMENU_START = "ADDMENU_START";
export const ADDMENU_END = "ADDMENU_END";
export const ADDMENU_FAIL = "ADDMENU_FAIL";
export const ADDMENU_SUCCESS = "ADDMENU_SUCCESS";
export const ADDMENU_EDIT = "ADDMENU_EDIT";
export const GET_ADDMENU_SUCCESS = "GET_ADDMENU_SUCCESS";
export const MENU_FILTER = "MENU_FILTER";
