export const ADDALACUENTA_START = "ADDALACUENTA_START";
export const ADDALACUENTA_END = "ADDALACUENTA_END";
export const ADDALACUENTA_FAIL = "ADDALACUENTA_FAIL";
export const ADDALACUENTA_SUCCESS = "ADDALACUENTA_SUCCESS";
export const ADDALACUENTA_EDIT = "ADDALACUENTA_EDIT";
export const SET_ADDALACUENTA_SUCCESS = "SET_ADDALACUENTA_SUCCESS";
export const SET_ADDALACUENTA_DINAMICO_SUCCESS =
  "SET_ADDALACUENTA_DINAMICO_SUCCESS";
export const SET_LISTAPEDIDOSPENDIENTES = "SET_LISTAPEDIDOSPENDIENTES";
export const GET_LISTAPEDIDOSPENDIENTES = "GET_LISTAPEDIDOSPENDIENTES";
export const GET_PRODUCTSDETAILS = "GET_PRODUCTSDETAILS";
export const EDIT_LISTA_PRODUCTOS = "EDIT_LISTA_PRODUCTOS";
export const SET_PARA_PRODUCTOS = "SET_PARA_PRODUCTOS";
