export const CATEGORIES_START = "CATEGORIES_START";
export const CATEGORIES_END = "CATEGORIES_END";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_EDIT = "CATEGORIES_EDIT";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
