export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_END = "PRODUCT_END";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_EDIT = "PRODUCT_EDIT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
