export const COBRARPEDIDO_START = "COBRARPEDIDO_START";
export const COBRARPEDIDO_END = "COBRARPEDIDO_END";
export const COBRARPEDIDO_FAIL = "COBRARPEDIDO_FAIL";
export const SET_COBRARPEDIDO_SUCCESS = "SET_COBRARPEDIDO_SUCCESS";
